#Use secrets in plaintext, they'll be encoded to base64 automatically.
secrets:
  data:
  - key: POSTGRESQL_PASSWORD
    value: "change-me"
  - key: WEBHOOK_TOKEN
    value: "XXXXXXXXXXXXXXXXXXXX"
#  - key: AZURE_ACCOUNT_KEY  # token with read write access to AZURE_BLOB_CONTAINER_CI_LOG and AZURE_BLOB_CONTAINER_CI_CACHE ,optional, if not provided pod identity will be used for authentication
#    value: "#########"

configs:
  BASE_URL_SCHEME: "http"
  #url without scheme and without trailing '/'
  BASE_URL: "www.example.com"
  #DEX_CONFIG: |-
  #  connectors:
  #    - type: oidc
  #      id: google
  #      name: Google
  #      config:
  #        issuer: https://accounts.google.com
  #        clientID: xxxxxxxx-xxxxxxxxxxxxxxxxx.apps.googleusercontent.com
  #        clientSecret: xxxxxxxxxxxxxxxxx
  #        redirectURI: <BASE_URL_SCHEME>://<BASE_URL>/api/dex/callback
  #        hostedDomains:
  #        - example.com
  DEFAULT_CD_LOGS_BUCKET_REGION: "change-me"
  DEFAULT_CACHE_BUCKET: "devtron-ci-cache"
  DEFAULT_CACHE_BUCKET_REGION: "change-me"
  DEFAULT_BUILD_LOGS_BUCKET: "devtron-ci-log"
  EXTERNAL_SECRET_AMAZON_REGION: ""
  PROMETHEUS_URL: "http://change-me/prometheus"
  BLOB_STORAGE_PROVIDER: "MINIO" # AZURE| GCP| S3 | MINIO
  #AZURE_ACCOUNT_NAME: "test-account"  # blob storage account name
  #AZURE_BLOB_CONTAINER_CI_LOG: "ci-log-container"  # container for ci log
  #AZURE_BLOB_CONTAINER_CI_CACHE: "ci-cache-container" #container for ci cache,  -> versioning policy similar to aws

