# Source: chartmuseum/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: devtron-chartmuseum
  labels:
    app: chartmuseum
    chart: chartmuseum-2.13.2
    release: "devtron"
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devtron-chartmuseum
  labels:
    app: chartmuseum
    chart: chartmuseum-2.13.2
    release: "devtron"
data:
  CHARTMUSEUM_STORAGE: amazon
  CHARTMUSEUM_STORAGE_AMAZON_PREFIX: "devtron-chartmuseum"
---
# Source: chartmuseum/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: devtron-chartmuseum
  labels:
    app: chartmuseum
    chart: chartmuseum-2.13.2
    release: "devtron"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: chartmuseum
    release: "devtron"
---
# Source: chartmuseum/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devtron-chartmuseum
  annotations:
    {}
  labels:
    app: chartmuseum
    chart: chartmuseum-2.13.2
    release: "devtron"
spec:
  selector:
    matchLabels:
      app: chartmuseum
      release: "devtron"
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  revisionHistoryLimit: 10
  template:
    metadata:
      name: devtron-chartmuseum
      annotations:
        {}
      labels:
        app: chartmuseum
        release: "devtron"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: chartmuseum
        image: chartmuseum/chartmuseum:v0.12.0
        imagePullPolicy: IfNotPresent
        env:
        - name: "CHART_POST_FORM_FIELD_NAME"
          value: "chart"
        - name: "DISABLE_METRICS"
          value: "true"
        - name: "LOG_JSON"
          value: "true"
        - name: "PROV_POST_FORM_FIELD_NAME"
          value: "prov"
        - name: "STORAGE"
          valueFrom:
            configMapKeyRef:
              name: devtron-chartmuseum
              key: "CHARTMUSEUM_STORAGE"
        - name: "STORAGE_AMAZON_BUCKET"
          valueFrom:
            configMapKeyRef:
              name: devtron-chartmuseum
              key: "CHARTMUSEUM_STORAGE_AMAZON_BUCKET"
        - name: "STORAGE_AMAZON_PREFIX"
          valueFrom:
            configMapKeyRef:
              name: devtron-chartmuseum
              key: "CHARTMUSEUM_STORAGE_AMAZON_PREFIX"
        - name: "STORAGE_AMAZON_REGION"
          valueFrom:
            configMapKeyRef:
              name: devtron-chartmuseum
              key: "CHARTMUSEUM_STORAGE_AMAZON_REGION"
        args:
        - --port=8080
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: http
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /health
            port: http
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
      volumes:
      - name: storage-volume
        emptyDir: {}