# Source: postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-migrator
  labels:
    app: postgresql
    chart: postgresql-8.6.4
    release: "devtron"
type: Opaque
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-migrate-orchestrator
spec:
  template:
    spec:
      containers:
      - name: postgresql-migrate-orchestrator
        image: 686244538589.dkr.ecr.us-east-2.amazonaws.com/release/migrator:0.0.1-rc23
        env:
        - name: GIT_BRANCH
          value: release-candidate
        - name: SCRIPT_LOCATION
          value: scripts/sql/
        - name: GIT_REPO_URL
          value: https://github.com/devtron-labs/devtron.git
        - name: DB_TYPE
          value: postgres
        - name: DB_USER_NAME
          value: postgres
        - name: DB_HOST
          value: postgresql-postgresql.devtroncd
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: orchestrator                      
        - name: MIGRATE_TO_VERSION
          value: "0"
        - name: GIT_HASH
          value: 1e307a163f8fbb658d59be07ce0fb19d286beb2e
        envFrom:
          - secretRef:
              name: postgresql-migrator
          # remove this
          - secretRef:
              name: migrator-git-secret
      restartPolicy: OnFailure
  backoffLimit: 1
  activeDeadlineSeconds: 1500
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-migrate-casbin
spec:
  template:
    spec:
      containers:
      - name: postgresql-migrate-casbin
        image: 686244538589.dkr.ecr.us-east-2.amazonaws.com/release/migrator:0.0.1-rc23
        env:
        - name: SCRIPT_LOCATION
          value: scripts/casbin/
        - name: GIT_REPO_URL
          value: https://github.com/devtron-labs/devtron.git
        - name: DB_TYPE
          value: postgres
        - name: DB_USER_NAME
          value: postgres
        - name: DB_HOST
          value: postgresql-postgresql.devtroncd
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: casbin
        - name: MIGRATE_TO_VERSION
          value: "0"
        - name: GIT_HASH
          value: 1e307a163f8fbb658d59be07ce0fb19d286beb2e
        - name: GIT_BRANCH
          value: master
        envFrom:
          - secretRef:
              name: postgresql-migrator
          - secretRef:
              name: migrator-git-secret
      restartPolicy: OnFailure
  backoffLimit: 1
  activeDeadlineSeconds: 1500
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-migrate-gitsensor
spec:
  template:
    spec:
      containers:
      - name: postgresql-migrate-gitsensor
        image: 686244538589.dkr.ecr.us-east-2.amazonaws.com/release/migrator:0.0.1-rc23
        env:
        - name: SCRIPT_LOCATION
          value: scripts/sql/
        - name: GIT_REPO_URL
          value: https://github.com/devtron-labs/git-sensor.git
        - name: DB_TYPE
          value: postgres
        - name: DB_USER_NAME
          value: postgres
        - name: DB_HOST
          value: postgresql-postgresql.devtroncd
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: git_sensor
        - name: MIGRATE_TO_VERSION
          value: "0"
        - name: GIT_BRANCH
          value: master
        - name: GIT_HASH
          value: 5329353a4b7de5640341ee5b70057f8becc3f491
        envFrom:
          - secretRef:
              name: postgresql-migrator
          - secretRef:
              name: migrator-git-secret
      restartPolicy: OnFailure
  backoffLimit: 1
  activeDeadlineSeconds: 1500
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-migrate-lens
spec:
  template:
    spec:
      containers:
      - name: postgresql-migrate-lens
        image: 686244538589.dkr.ecr.us-east-2.amazonaws.com/release/migrator:0.0.1-rc23
        env:
        - name: SCRIPT_LOCATION
          value: scripts/sql/
        - name: GIT_REPO_URL
          value: https://github.com/devtron-labs/lens.git
        - name: DB_TYPE
          value: postgres
        - name: DB_USER_NAME
          value: postgres
        - name: DB_HOST
          value: postgresql-postgresql.devtroncd
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: lens
        - name: MIGRATE_TO_VERSION
          value: "0"
        - name: GIT_BRANCH
          value: master
        - name: GIT_HASH
          value: 772fcb2a4b3198879efb6139ed3a27dfb40ed681
        envFrom:
          - secretRef:
              name: postgresql-migrator
          - secretRef:
              name: migrator-git-secret
      restartPolicy: OnFailure
  backoffLimit: 1
  activeDeadlineSeconds: 1500